### ISSUE TITLE
プロジェクトごとに違う開発環境の管理について

### ISSUE THREAD

**Issue by watilde** [codegrid/party-2017-05#5]
## 質問のタイトル（Issueタイトル）
プロジェクトごとに違う開発環境の管理について

## 質問の具体的な内容があればお願いします
+ 表題に関して <img width=16 height=16 alt="ﾋﾟｸｸﾞﾘ!" src="https://cloud.githubusercontent.com/assets/1716463/24995273/8c44274e-202e-11e7-919c-51d9b167fe9a.png" />さんでは、どのように管理していますか？
+ どの程度チーム内で統一させていますか？

**Comment by ykhs** [comment]
## 回答

- Node.jsのバージョンはndenvと`.node-version`でそれとなく揃えてる
    - 必須ではなく便利だと思う人は使うという程度
- OSはいま全員たまたまmacOSを使っている状態
    - セキュリティ面の理由で古いバージョンのまま使わないようにという社内規定はある
- `package.json`の`dependencies`更新時はチャットで号令かけて追従してもらう
- 案件がフロントエンド特化のため悩みが少ない面もある
    - データベースや他の言語環境を整える必要のある場面が少ない
        - その辺りも必要な場合は開発環境のDocker化も検討している

**Comment by watilde** [comment]
ご回答ありがとうございました！
