### ISSUE TITLE
ReactやAngular、VueのコンポーネントとCSSの関係

### ISSUE THREAD

**Issue by tacamy** [codegrid/party-2017-05#7]
よく、CSSのコンポーネントの粒度とJSのフレームワークのコンポーネントの粒度が違うから、CSSは別ファイルで今までどおりBEMとか使ってCSS設計する、みたいな話をよく聞くけど、本当にそうなのかなと最近悩ましいです。

たとえば、material-uiでは、コンポーネント自体にCSSも含まれていて、使う側としては使いたいコンポーネントをただimportするだけで見た目も動きも全部がセットになっていて使いやすいなと思いました。
スタイルを調整したいときは、コンポーネントを使うときにスタイルを上書きできるように作られているので、同じ機能だけど似たような見た目でチョット違うみたいなことにも対応できるし。

擬似的にでもJSのコンポーネントの単位でCSSのScopeを作れるのであれば、そもそもCSSの設計とかあんまり必要性を感じないような気もしていて。

また、JSのコンポーネントにCSSも含まれていれば、コンポーネント自体が不要になったときに、コンポーネントを捨てるだけで不要なスタイルが残ることもないし、「捨てやすい」構造にもなるのかなと。

とはいえ、私はReactでインラインでスタイルを書くか、Vueでコンポーネント単位でstyleにscopedつけてつくるかしかしたことがないので、他のフレームワークではどうなのかとか、ReactでもCSSをインラインで書かない場合はどうなのかとか、いろいろな意見を聞きたいです。

**Comment by usagi-f** [comment]
ほぼ同じ疑問を持っています。

私は逆にCSS in JSに疑問を感じていて、
CSSもコンポーネントに含まれていた場合、UIの扱いはとても便利なのですが

- ビルド時に依存するもの（*-loader）の増加
- SSRが必要なときにとても複雑になる（isomophic-style-loaderはアリなのか？）
- アクセシビリティ観点での問題
- 自動的に<style>で展開される気持ち悪さ（これは解決法がありますが）

など、弊害が多いように感じています。

別の手段でもCSSのScopeはつくることが出来ると思うので、
上記すべて抱え込んでまでやる必要性がどれだけあるのか？気になっています。

**Comment by geckotang** [comment]
パーティでは、4人のエンジニアがそれぞれの経験を話しました。

## 回答

## tacamyの場合

### ReactでのCSS

- オブジェクト形式でスタイルを書いている
- `:hover`などの擬似クラスや疑似要素はJSで表現する必要があるが、思っていたよりも大変ではなかった
- メディアクエリに関しては、[react-responsive](https://github.com/contra/react-responsive)を使用した

### VueでのCSS

- Vueでは2つの方法を経験しました。
    1. いつものようにグローバルにBEM等でCSSを書きコンポーネントごとには書かない
    1. コンポーネントごとにscopedで書く方法
- 2のほうが、コンポーネントごとに独立する
- そのコンポーネントに書いたCSSが外部に影響することもなく
- 不要になったら気軽に削除することもできる

## geckotangの場合

### Angular 4.xでのCSS

- 私の案件においては、コンポーネントの粒度をJSのエンジニアが決定する
    - コンポーネントによっては1ページが1コンポーネントの場合もある
- コンポーネントごとにscopedで書いている
- 似たようなボタンが別々のコンポーネントにあっても、CSSをコピペしてそれぞれのコンポーネントに記述する
- デメリットとしては、修正があった場合に、各コンポーネントのCSSを精査する必要がでてくる
- 「他のコンポーネントに影響を及ぼさない」「気軽に削除できる」ことを重要視しているので、デメリットを覚悟してもメリットのほうが大きい
- 今の案件は「細かいコンポーネントを組み合わせてページを作っていく」というスタンスではないので、成立しているのかもしれない
- [ECSS](http://ecss.io/)の設計方法に近いのかなと思っています。


## neotagの場合

### ReactでのCSS

- ピュアにBEMでコンポーネント化
- CSS in JS 的なことを考慮に入れてリファクタ
- CSS Modules に乗り換え進行中

## yoshiko_pgの場合

### ReactでのCSS

- http://yoshiko.hatenablog.jp/entry/css-in-js
- [styled-components](https://github.com/styled-components/styled-components)を使用している
- Reactで作る既存のコンポーネントにスタイルを適用するのではなく、styled-componentsでスタイル用の新たなコンポーネントを作っている
- ロジック用コンポーネントにクラスつけるよりもさらにロジックとスタイルが疎になる
- スタイル用のコンポーネントは異なる挙動のReactコンポーネント間で自由に使いまわせる
- ロジック用コンポーネントにクラスつけるよりもさらにロジックとスタイルが疎になる
- Devtoolで見たときにこれがこのコンポーネントっていうのの手がかりが少ない
- ロジック用コンポーネントとスタイル用コンポーネントが別なので要素数が増えがち（柔軟性とトレードオフなので仕方ない）
- flexboxとかgridみたいな直下の要素がitemになるものは階層が関係するのでちょっと気を使う

## まとめ

- 捨てられる事が重要
- あくまで、答えの一つであって、最適解ではない。
- 大体は、プロジェクトによる。
- デザインの方針だったり、使いまわすことが前提かどうかで、どういった方法でCSSを書くか検討する

**Comment by tacamy** [comment]
ご回答ありがとうございました！
